language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
      env: COMPOSER_INSTALL_FLAGS=--ignore-platform-reqs
  allow_failures:
    - php: 7.4snapshot
    - php: nightly

branches:
  only:
    - master

script:
  - travis_retry composer install --no-interaction --prefer-dist ${COMPOSER_INSTALL_FLAGS}

cache:
  directories:
    - $HOME/.composer/cache/files