language: php

php:
  - '7.3'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer install --no-interaction --prefer-dist
 
script:
  - vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache/files